### ISSUE TITLE
Selenium-cucumber console

### ISSUE THREAD

**Issue by AlexWellsHS** [selenium-cucumber/selenium-cucumber-ruby#24]
I'm not sure if this is the right place for this question, but does Selenium-cucumber have a "console" option akin to calabash's [calabash-ios console](https://github.com/calabash/calabash-ios/blob/da2fce369ec64d4957718b2a8d66c4c807421274/calabash-cucumber/bin/calabash-ios-build.rb)? 
When I start an irb and attempt to require "selenium-cucumber", I get the following NoMethod error:

```
➜  selenium-test irb
irb(main):001:0> require "selenium-cucumber"
NoMethodError: undefined method `Then' for main:Object
    from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-cucumber-3.1.5/lib/selenium-cucumber/assertion_steps.rb:4:in `<top (required)>'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-cucumber-3.1.5/lib/selenium-cucumber.rb:1:in `block in <top (required)>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-cucumber-3.1.5/lib/selenium-cucumber.rb:1:in `each'
    from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-cucumber-3.1.5/lib/selenium-cucumber.rb:1:in `<top (required)>'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
    from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from (irb):1
    from /usr/local/bin/irb:11:in `<main>'
irb(main):002:0>
```

I assume there is a way to load the selenium-cucumber api helpers into an irb, but I just don't know how. Any help would be much appreciated!

**Comment by Carlbc18** [comment]
@AlexWellsHS I'll look into this. Thanks for posting.

**Comment by sameer49** [comment]
@AlexWellsHS No we have not implemented selenium-cucumber console yet.
